### ISSUE TITLE
need to create a refresh button to clear local storage or simply delete the values in html css or js

### ISSUE THREAD

**Issue by ScorchingShade** [ScorchingShade/Codera#1]
basically it needs a clear all button

**Comment by cdterry87** [comment]
I would like to try this one, if that's okay.

**Comment by vickyktk** [comment]
`wait I am doing a PR...I shall do it`

**Comment by gpsuhas20** [comment]
i am interested to do this task please assign me this task i have experience working with local stoarge

**Comment by ScorchingShade** [comment]
Please clone the repo, i am not specifically assigning this to anyone. When the pull request is generated, i will verify the same

**Comment by DreamsOfImran** [comment]
Created PR for it. Please review.
https://github.com/ScorchingShade/Codera/pull/7/

**Comment by ScorchingShade** [comment]
reviewing

**Comment by ScorchingShade** [comment]
This issue has been fixed. please refer to the new issue for more work. Thanks and congratulations for contributing towards your goal of hacktoberfest 2020
