### ISSUE TITLE
Dependencies are missing in package.json file

### ISSUE THREAD

**Issue by DreamsOfImran** [ScorchingShade/Codera#2]

**Comment by DreamsOfImran** [comment]
Can you assign this to me?

**Comment by Rajdeepc** [comment]
@ScorchingShade   How did you make an application without any dependencies in the project? 
I am sure you have not run this application before. Please create a concrete application and open issues or else this repository will be marked as stale.

**Comment by ScorchingShade** [comment]
Hi @rajdeepc , this project runs well. You can view a demo at https://pensive-einstein-f139d4.netlify.app/

You can create a pr with the missing dependencies added and i will merge it
