### ISSUE TITLE
local storage storing values as "undefined"

### ISSUE THREAD

**Issue by avnish1306** [ScorchingShade/Codera#5]
local storage was storing values as undefined due to which the default value of rendered content was "undefined" and this issue was also causing "cross origin errors".
![image](https://user-images.githubusercontent.com/28188933/95012363-8fd4b200-0655-11eb-99d8-945477761762.png)

**Comment by avnish1306** [comment]
@ScorchingShade, I already fixed this issue, Please assigned this to me. I'll merge the fix.

**Comment by DreamsOfImran** [comment]
Clear your site storage and refresh. It will work

**Comment by avnish1306** [comment]
Yes I know but this issue should be fixed. 
![image](https://user-images.githubusercontent.com/28188933/95012445-3a4cd500-0656-11eb-9a45-979e79050a7e.png)
By default it's showing "undefined".

**Comment by ScorchingShade** [comment]
I have assigned the issue to you @avnish1306
