### ISSUE TITLE
Need UI adjustments and beautification for the refresh button

### ISSUE THREAD

**Issue by ScorchingShade** [ScorchingShade/Codera#8]
Please use material design and icons to make the refresh button look appealing

**Comment by symtalha14** [comment]
I would like to work on this. Please assign me.

**Comment by ScorchingShade** [comment]
Sure, please raise a PR after you are done working, I will review

**Comment by symtalha14** [comment]
You haven't assigned me though :) Is it alright?

**Comment by ScorchingShade** [comment]
This works?

**Comment by symtalha14** [comment]
Please review my PR. Let me know any changes.

**Comment by ScorchingShade** [comment]
Please resolve conflicts

**Comment by ScorchingShade** [comment]
This issue has been closed now
